server:
  port: 8080

Spring:
  datasource:
    username: {your username}
    password: {your password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/{your database}?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

# 数据库表会自行创建，根据model层User改变而改变
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
